server:
  port: 8082

spring:
  application:
    name: analytics-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/analyticsdb}
    username: ${SPRING_DATASOURCE_USERNAME:analytics}
    password: ${SPRING_DATASOURCE_PASSWORD:analytics123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
