global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9249']

  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8082']
