server:
  port: 8081

spring:
  application:
    name: kafka-streams-processor
  kafka:
    streams:
      application-id: sales-processor
      bootstrap-servers: ${SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        auto.offset.reset: earliest

target:
  db:
    url: ${TARGET_DB_URL:jdbc:postgresql://localhost:5433/analyticsdb}
    user: ${TARGET_DB_USER:analytics}
    password: ${TARGET_DB_PASSWORD:analytics123}

openlineage:
  url: ${OPENLINEAGE_URL:http://localhost:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
